version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodefrontend
      - nodebackend
    networks:
      - node-exa

  nodefrontend:
    container_name: nodefrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-exa
    depends_on:
      - node-db
      - nodebackend
    command: npm start
    environment:
      - CHOKIDAR_USEPOPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=/api

  nodebackend:
    container_name: nodebackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: node-db
      DB_USER: root
      DB_PASSWORD: "12345678"
      DB_NAME: newappec
    networks:
      - node-exa
    depends_on:
      - node-db
    command: npm start

  node-db:
    image: mysql:8.0
    container_name: node-db
    environment:
      MYSQL_DATABASE: "newappec"
      MYSQL_ROOT_PASSWORD: "12345678"
    volumes:
      - db:/var/lib/mysql
      - ./tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    networks:
      - node-exa

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: node-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - node-exa

networks:
  node-exa:
    driver: bridge

volumes:
  db:
    driver: local
